# Generated by Django 5.2.15 on 2026-07-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(max_length=50, unique=True, verbose_name='Equipment ID')),
                ('equipment_name', models.CharField(max_length=100, verbose_name='Equipment Name')),
                ('model_type', models.CharField(max_length=100, verbose_name='Type / Model')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial Number')),
                ('capacity', models.CharField(blank=True, max_length=50, null=True, verbose_name='Capacity')),
                ('area', models.CharField(choices=[('PRODUCTION', 'Production Area'), ('WORKSHOP', 'Maintenance Workshop'), ('UTILITY', 'Utility & Power House'), ('WAREHOUSE', 'Warehouse & Logistics'), ('OFFICE', 'Administration Office')], default='PRODUCTION', max_length=50, verbose_name='Area')),
                ('location', models.CharField(max_length=255, verbose_name='Specific Location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['equipment_id'],
            },
        ),
    ]
