# Generated by Django 5.2.15 on 2026-07-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['equipment_id']},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='area',
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Area & Location'),
        ),
    ]
