# Generated by Django 5.2.15 on 2026-07-03 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_options_remove_asset_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['created_at']},
        ),
    ]
