# Generated by Django 5.2.15 on 2026-07-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100, unique=True, verbose_name='Part Number / SKU')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Suku Cadang')),
                ('stock', models.IntegerField(default=0, verbose_name='Stok Saat Ini')),
                ('min_stock', models.IntegerField(default=5, verbose_name='Stok Minimum (Alert)')),
                ('location', models.CharField(blank=True, help_text='Contoh: Rak A-02', max_length=100, null=True, verbose_name='Lokasi Rak')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Spare Part',
                'ordering': ['name'],
            },
        ),
    ]
