# Generated by Django 5.2.15 on 2026-07-03 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_alter_asset_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_number', models.CharField(max_length=50, unique=True, verbose_name='Work Order Number')),
                ('title', models.CharField(max_length=200, verbose_name='Job Title')),
                ('description', models.TextField(verbose_name='Description / Instructions')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('EMERGENCY', 'Emergency / Breakdown')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Created / Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending / On Hold'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='CREATED', max_length=20)),
                ('downtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Downtime (Hours)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='assets.asset', verbose_name='Asset ID')),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
