# Generated by Django 5.2.15 on 2026-07-03 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderPartConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField(default=1, verbose_name='Jumlah Digunakan')),
                ('consumed_at', models.DateTimeField(auto_now_add=True)),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wo_usages', to='inventory.sparepart')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_consumptions', to='workorders.workorder')),
            ],
            options={
                'verbose_name': 'WO Part Consumption',
                'unique_together': {('work_order', 'spare_part')},
            },
        ),
    ]
