# Generated by Django 5.2.15 on 2026-07-03 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_alter_asset_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventiveSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Mingguan'), ('MONTHLY', 'Bulanan'), ('QUARTERLY', '3 Bulanan (Kuartal)'), ('SEMI_ANNUALLY', '6 Bulanan'), ('ANNUALLY', 'Tahunan')], default='MONTHLY', max_length=20)),
                ('next_due_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_schedules', to='assets.asset')),
            ],
            options={
                'verbose_name': 'Preventive Schedule',
                'ordering': ['next_due_date'],
            },
        ),
    ]
